---
language: python
python: "2.7"
cache: pip

install:
  - pip install ansible awscli boto
  - "{ echo '[defaults]'; echo 'roles_path = ../:../../:../../../'; } >> ansible.cfg"

script:
  - ansible-playbook -i tests/inventory tests/test.yml --syntax-check
